version: '3'
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/authentication/app/:/code/app
    env_file:
      - ./backend/authentication/app/.env
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - cache

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - backend/authentication/app/.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  cache:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - cache:/data
    command: redis-server --requirepass 3050132596


volumes:
  postgres-db:
  cache:
    driver: local
