version: '3'
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/authentication/app/:/code/app
    env_file:
      - backend/authentication/.env
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - backend/authentication/.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redis_cache:/data
    environment:
      #      - REDIS_PASSWORD=3050132596
      - REDIS_IO_THREADS_DO_READS=true
      - REDIS_IO_THREADS=4
    command: redis-server --requirepass 3050132596


volumes:
  postgres-db:
  redis_cache:
    driver: local
